### ISSUE TITLE
Twitter Bot Bootstrap - Sentiment Analysis

### ISSUE THREAD

**Issue by xianshun** [spences10/ama#1]
Hi Scott,

Thanks for the great tutorial for the twitter bot! I would like to add the same feature you have for the 100 days of code bot. The feature being "It will also reply with encouragement if it detects negative sentiment (frustration) in a tweet that has the #100DaysOfCode hashtag in it". If you have documentation regarding how to do this, it would be much appreciated if you could pass it along. Thanks.

**Comment by spences10** [comment]
Hey @xianshun,

Thanks for the question, that piece of work was was done by @Ilyes-Hammadi and I have tried to implement it elsewhere in other projects such as:

[positivity](https://github.com/spences10/positivity)

I have some of the functionality working but it's very much trial and error, if you find anything feel free to let me know.

Thanks

**Comment by xianshun** [comment]
Thanks Scott
