### ISSUE TITLE
Can your "table of content example" go back to main content when using mobile/iPad?

### ISSUE THREAD

**Issue by kingchun1991** [spences10/ama#10]
Great tutorial:

https://scottspence.com/2020/02/13/smooth-scroll-toc-gatsby/#-heres-a-video-detailing-the-process

I wonder if the table of content can get back into the main content for responsive design￼￼￼￼?

**Comment by spences10** [comment]
Hey @kingchun1991, 

Glad you got something out of the content, thanks.

I'm not sure what you mean here??

Do you mean the main content as in away from the current post? If that's the case then use the nav items it the top of the screen, right?

**Comment by kingchun1991** [comment]
![image](https://user-images.githubusercontent.com/13637838/88173726-a625c100-cc55-11ea-95a3-0a574b502e0b.png)

I mean the left table of content div go into the article when using mobile device to view.

**Comment by spences10** [comment]
Oh, ok, my opinion (for my site) is that on mobile you're scrolling so there's no real need for it.

If you want to implement something on your own site then I'd suggest doing it with a media query with CSS grid.

So, yes, absolutely possible with media queries and CSS grid if you're supporting browsers that don't support grid then possibly something with JS

**Comment by kingchun1991** [comment]
Thank you.
Again your table of contents are really great👍🏽
