### ISSUE TITLE
Blog Performance with CMS - Gatsby/Strapi

### ISSUE THREAD

**Issue by dorukcanyolacan** [spences10/ama#12]
You have a blog with a good performance metrics by only using Gatsby (even better than Gatsby's official blog). However, i was wondering, if you had any experience with CMS solutions to integrate and still kept the performance good enough. I was experimenting with Strapi-Gatsby, but doesn't look promising enough. Do you have any recommendations or possible solutions to look for?

(By performance, I'm considering [web.dev](url) results as an indicator)

**Comment by spences10** [comment]
Hey @dorukcanyolacan!

Great question and one me and my team have had to consider on several occasions, the answer is an uninspiring "it depends"

Depends on how many pages you intend to generate and how often you want to generate them, with Gatsby if you have a really large site then the page builds (particularly with a lot of images) will be what will take a large chunk of the build time, there are solutions like cacheing which Jason Lengstorf goes into detail with Benjamin Lannon on [Learn with Jason] about or you can use a third party service like Cloudinary.

I have used GraphCMS and Strapi but only for demonstration purposes in the past.

As I'm not aware of where you're bottlenecks are I can't really offer up anything specific other than what I know of as the main pain points in Gatsby for large sites.

[learn with jason]:https://www.learnwithjason.dev/caching-jamstack-sites-with-github-actions
