### ISSUE TITLE
Adding a blog to an existing Gatsby site

### ISSUE THREAD

**Issue by san00** [spences10/ama#14]
Hi Scott,

I'm fairly new to Gatsby & have an existing gatsby site that I have added an MDX blog to. My issue is I don't want the blog posts to appear on the home/index page of my site and instead want to link to the blog from the main nav.
My question is, what's the best way of doing this? Do I need to build the blog as a standalone site that I then link to the main website or is there a better approach? 
I've looked for answers elsewhere, but have not found anything, so thought I'd ask.

**Comment by spences10** [comment]
Hey thanks for reaching out @san00!

What I'd do is create another page (in `src/pages`) that will contain all the posts you want for the blog then point to that.

Example:

```text
may-awesome-site/
├─ src/
│   └─ pages
│     └─ about.js
│     └─ blog.js
│     └─ contact.js
│     └─ index.js
```

Then in `blog.js` map over your posts:

```js
import { graphql, Link } from "gatsby";
import React from "react";
import { Layout } from "../components/layout";

export default function BlogPage({ data }) {
  return (
    <>
      <Layout>
        {data.allMdx.nodes.map(({ id, excerpt, frontmatter, slug }) => (
          <article
            key={id}
          >
            <Link to={`/${slug}`}>
              <h2>{frontmatter.title}</h2>
              <p>
                {frontmatter.date}
              </p>
              <p>
                {excerpt}
              </p>
            </Link>
          </article>
        ))}
      </Layout>
    </>
  );
}

export const query = graphql`
  query SITE_INDEX_QUERY {
    allMdx(sort: { fields: [frontmatter___date], order: DESC }) {
      nodes {
        id
        excerpt(pruneLength: 250)
        frontmatter {
          title
          date(formatString: "YYYY MMMM Do")
        }
        slug
      }
    }
  }
`;
```

**Note that GraphQL query is for MDX I'm not sure what you're using for sourcing the posts**

Then you'll have a list of your blog posts in a different route from your index page.

I have made an extensive posts on getting a blog set up with Gatsby and MDX on [Sitepoint] with examples if you want to take a look at that it may help.

If you have a link to the source I can take a look for you if you like, the majority of the points to get going are covered in the Sitepoint post however.

Thanks.

[sitepoint]: https://www.sitepoint.com/gatsby-mdx-blog/
