### ISSUE TITLE
Thank you so much for the tutorial

### ISSUE THREAD

**Issue by hugoleonardodev** [spences10/ama#15]
Hi Scott,

My name is Hugo, I'm a front-end developer from Belo Horizonte, Brazil.

I was enjoying all the potential that Gatsby has with TypeScript when I got stuck with Styled Components configurations.
My whole weekend was going when I finally found your tutorial about it.

[Globally Style the Gatsby Default Starter with styled-components v5](https://scottspence.com/posts/globally-style-gatsby-styled-components)

Thank you so much for sharing.

By the way, I'm looking for remote work abroad. And the UK is the best place. Since we have a current ratio of more than 7:1 here comparing UK pound sterling to Brazilian Real. I could not lose the opportunity to say that.

With that being said, would like to thank you again. And I'm also writing a Gatsby blog to publish cool articles like yours.

See you on the web!

**Comment by spences10** [comment]
Hey Hugo!

Thanks so much for reaching out and it's always awesome to hear the stuff I'm putting out there makes a difference!

I'm not looking, neither do I know of anywhere that's looking for a full time remote front-end developer.

Thanks again 🙏
