### ISSUE TITLE
Love your TwitterBot article.  

### ISSUE THREAD

**Issue by djamesp1** [spences10/ama#2]
Thanks so much for your twitterBot article! Awesome.  I'm using your code as a template.  I particularly like the dotenv functionality for hiding the Twitter App keys when deploying to ZEIT.  I'm trying to adapt some other great code from:  https://github.com/tylerl0706/TechKnightsTwitterNodeDemo - (The Magic 8 Ball example),
but I want to incorporate into your code template, but can't seem to get it to work, possibly because it's using the twitter npm instead of twit, and also can't seem to get it to work with the dotenv environment variables.

You might find the Magic 8 ball code and functionality interesting yourself, and would be so thankful if you could help me adapt to jun in the same bot.js file in your tutorial?

Another question about ZEIT, I can't seem to figure out how to delete an instance from the ZEIT site?

Thx for all help and inspiration,
djamesp

**Comment by spences10** [comment]
Hey @djamesp1 thank you for your kind words 😄 

From looking at the `magic_8_ball.js` example it appears to be a random quote in reply to someone that tweets with the hashtag `#TechKnightsDemoMagic` correct?

What is it that you are struggling with? I checked your GitHub profile but couldn't see anything on there relating to a twitter bot...

Using the Twitter `stream.on` method is something I am considering adding to my bootstrap as it makes searching that little bit easier.

With regard to using `twitter` in place of `twit` would be a case of changing the package name, so looking Tyler's example if you want to use `twit` instead to `twitter` import the `twit` package:

```bash
npm i twit
```

Then you can replace the `require`'s statement:

```js
var TwitterPackage = require('twit')
```

They both seem to use the same input values for the Twitter API keys so they could probably be used interchangeably.

Take a look at my [twitter-bot-playground](https://github.com/spences10/twitter-bot-playground) repo, the book is here: https://spences10.gitbooks.io/twitter-bot-playground/content/

The first section goes over setting up a new bot: https://spences10.gitbooks.io/twitter-bot-playground/content/docs/00-set-up-the-bot.html#set-up-the-bot

For the 8 ball random quote take a look at the [random reply](https://github.com/spences10/twitter-bot-bootstrap/blob/5a00ec24a61459c5189d5c538e0e48804ef31c5d/src/api/reply.js#L6) on the Twitter bot bootstrap, it does the same sort of thing 👍
