### ISSUE TITLE
Please help me to solve my error regarding Twitter bot

### ISSUE THREAD

**Issue by gshyamg8** [spences10/ama#4]
I have written a JavaScript code for Twitter bot.
After that.Twitter restricted my writing access cause of too many requests.
So now I have to add stream to it (I don't know how)
And make it go slower (I also don't know about it )

Please help me to solve those issues

**Comment by spences10** [comment]
Hi @gshyamg8, Twitter has become a bit less tolerant of the API being used for automated purposes.

Take a look at the https://github.com/spences10/delay-tweet repo it does both the features you have asked for 👍
