### ISSUE TITLE
Other social media

### ISSUE THREAD

**Issue by dev6841** [spences10/ama#5]
Hi Scott.  I read your article on twitter bots.  Great article.  Thanks.  I'm new to the field.  Am I correct to assume that similar methodology for Twitter bots can be applied to create bots for Facebook, YouTube, Instagram or other social media?  Thanks, dev6841.

**Comment by spences10** [comment]
@dev6841 I'm so sorry, I appear to have missed this question.

Yes there are similar platforms, the one I spent a bit of time with was the [Microsoft Bot Framework] it was quite easy to configure and there are some good resources on getting set up with it,

[Microsoft Bot Framework]: https://dev.botframework.com/
