### ISSUE TITLE
Twitter bot Bootstrap new webhooks

### ISSUE THREAD

**Issue by MrVIncentRyan** [spences10/ama#6]
Hi Scott,

Thanks for the article on building the twitter bots. I followed it, deleted my work space and the followed your readme! 
Unfortunately I keep getting an error.

The bot found a tweet but I think the error must be in relation to retweeting. I am not sure
 )/ۜ SUCCESS: RT:  @danennis100 @cathshan @TodaySOR That joke doesn’t qualify as road worthy RANDO ID:  0
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Bad Twitter streaming request: 404

If you had a second that would be great. thanks

**Comment by spences10** [comment]
Hi @MrVIncentRyan,

Thanks for taking a look at the Twitter bots, unfortunately as I have't really had a look at the API for a good two years not I'm not in any position to give any relevant help.

Good luck.
