### ISSUE TITLE
Gatsby.js  how to set copy button  on each code in markdown ?

### ISSUE THREAD

**Issue by ghost** [spences10/ama#9]
hi!
I read your gatsby article (https://thelocalhost.blog/2019/10/31/build-an-mdx-blog/#code-blocks)
this is awesome.
And I am wondering how you get copy button in your markdown code. 
Is this plugin or something ?

**Comment by spences10** [comment]
Hey @nibu0215!

I've covered that part in a YouTube video [here] it's also [in the post].

Thanks :pray: 

[here]: https://www.youtube.com/watch?v=j-EINXVe2WA&list=PLGi_uHe_v04DRZ58L_0O5cilalymkC7On&index=16
[in the post]:https://thelocalhost.io/2019/10/31/build-an-mdx-blog/#copy-code-to-clipboard

**Comment by ghost** [comment]
Oh, I missed that part. :)
 thnaks !!
